name: CI
on:
  push:
    branches: ["develop"]
jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v6.0.0
      - name: pyInstall
        uses: actions/setup-python@v6.0.0
        with: 
          python-version: 3.14
      - name: install dependencies
        run: |
            pip install -r requiremenets.txt
      - name: run tests
        run : |
          pytest
      - name: Notify on failure
        if: failure()  
        run: |
              echo "Tests failed!"
          
